language: objective-c
osx_image: xcode7.3
install:
    - brew update
    - brew upgrade
    - brew install gpg2
    - gpg2 --recv-keys 7733D95B
    - sudo gem install cocoapods
    - pod repo update 2>&1 >/dev/null
    - pod install --verbose
    - xcodebuild -workspace NetProbe.xcworkspace/ -scheme NetProbe
      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
