language: objective-c
osx_image: xcode8
install:
    - brew update
    - brew install gpg2
    - gpg2 --recv-keys 7733D95B
    - sudo gem install cocoapods
    - pod repo update 2>&1 >/dev/null
    - pod install --verbose
    - sudo gem install xcpretty
    - set -o pipefail && xcodebuild -workspace ooniprobe.xcworkspace/
        -scheme ooniprobe CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          | xcpretty
